---
abstract: 'Set woothee information based on User-Agent'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  HTTP::Request::Common: 0
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Woothee
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::Middleware::Woothee:
    file: lib/Plack/Middleware/Woothee.pm
    version: 0.02
  Plack::Middleware::Woothee::Object:
    file: lib/Plack/Middleware/Woothee.pm
requires:
  Plack: 1
  Woothee: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/p5-Plack-Middleware-Woothee/issues
  homepage: https://github.com/Songmu/p5-Plack-Middleware-Woothee
  repository: git://github.com/Songmu/p5-Plack-Middleware-Woothee.git
version: 0.02
x_contributors:
  - 'Dai Okabayashi <bayashi@cpan.org>'
